from src.configs.fasttext_config import *
from src.configs.textcnn_config import *
from src.configs.transformer_config import *
from src.configs.textrcnn_config import *
from src.configs.bilstm_config import *
from src.configs.dpcnn_config import *
from src.configs.bert4keras_config import *
from src.configs.hf_config import *
from src.configs.emb_config import *
from src.configs.sklearn_config import *